services:
  nginx:
    image: nginx:1.25.3
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: ./app/
        target: /var/www/html/
    ports:
      - 8787:80
    depends_on:
      - php-fpm

  php-fpm:
    image: php:8.2-fpm
    volumes:
      - type: bind
        source: ./app/
        target: /var/www/html/